---
name: Test workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  peepoo:
    name: "PeePoo"
    # runs-on: debian-latest
    runs-on: self-hosted
    environment: test
    steps:
      - name: Run test command
        run: echo "hello world"
      - name: Echo test var
        run: echo "${{ vars.TEST_VAR }}"
      - name: Echo test secret
        run: echo "${{ secrets.TEST_SECRET }}"
      - name: Echo context
        run: echo $GITHUB_CONTEXT
      - name: Echo env
        run: env
      - name: Malicious intent
        run: uname -a
